### ISSUE TITLE
What is X-ExecFile for?

### ISSUE THREAD

**Issue by epicfaace** [keichan34/wordpress-on-lambda#1]
What do the X-ExecFile headers in this file (https://github.com/keichan34/wordpress-on-lambda/blob/master/src/php/handler.php) do?

Additionally, why is the code here (https://github.com/keichan34/wordpress-on-lambda/blob/master/src/php/handler.php#L20) needed?

**Comment by keichan34** [comment]
Sorry for the (really late) response!

`X-ExecFile` is for debugging. I wanted to make sure the correct file was being executed. You can safely delete it.

The code on `handler.php:20` is used to prevent `handler.php` itself from being executed (like `https://somewhere/handler.php`), which would result in an infinite loop of the `handler.php` script requiring itself. If you already have a file called `handler.php`, you might want to rename the file to something else like `__handler.php` or something like that.

Hope that clears things up! Let me know if you have any more questions :)

**Comment by epicfaace** [comment]
Thanks!
